services:
  # Backend API
  - type: web
    name: book-sharing-backend
    runtime: python
    buildCommand: "pip install poetry && poetry install --no-root"
    startCommand: "poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: book-sharing-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health

  # Frontend
  - type: web
    name: book-sharing-frontend
    runtime: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://book-sharing-backend.onrender.com
    healthCheckPath: /

databases:
  - name: book-sharing-db
    databaseName: book_sharing
    user: book_sharing_user
