"""fix_reviews_model_sqlite_compatibility

Revision ID: 8cd83edee68a
Revises: ff40704dc4af
Create Date: 2025-10-05 16:34:21.965455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd83edee68a'
down_revision = 'ff40704dc4af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_book_user_review'), 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_book_user_review'), 'reviews', ['book_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
