"""update books: soft delete + current_borrower

Revision ID: a4fee5145a80
Revises: 01322900dc91
Create Date: 2025-09-08 15:16:31.550414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fee5145a80'
down_revision = '01322900dc91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('current_borrower_id', sa.UUID(), nullable=True))
    op.add_column('books', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('books', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('books', sa.Column('archived_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_books_current_borrower_id'), 'books', ['current_borrower_id'], unique=False)
    op.create_foreign_key(None, 'books', 'users', ['current_borrower_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_current_borrower_id'), table_name='books')
    op.drop_column('books', 'archived_reason')
    op.drop_column('books', 'archived_at')
    op.drop_column('books', 'is_archived')
    op.drop_column('books', 'current_borrower_id')
    # ### end Alembic commands ###
