"""Fix group_id foreign key in loans table

Revision ID: a94d7c678de4
Revises: c4bcd84b18af
Create Date: 2025-09-10 20:11:53.421705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94d7c678de4'
down_revision = 'c4bcd84b18af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'loans', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    # ### end Alembic commands ###
