"""Add book_type and genre fields to Book model

Revision ID: c4bcd84b18af
Revises: e460490c0896
Create Date: 2025-09-10 19:58:56.378093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bcd84b18af'
down_revision = 'e460490c0896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tipos ENUM primero
    book_type_enum = sa.Enum('novel', 'comic', 'manga', 'graphic_novel', 'short_story', 'poetry', 'essay', 'biography', 'autobiography', 'other', name='book_type')
    book_type_enum.create(op.get_bind())
    
    book_genre_enum = sa.Enum('fiction', 'science_fiction', 'fantasy', 'mystery', 'thriller', 'horror', 'romance', 'historical_fiction', 'literary_fiction', 'adventure', 'western', 'dystopian', 'magical_realism', 'non_fiction', 'biography', 'autobiography', 'history', 'philosophy', 'psychology', 'science', 'technology', 'business', 'self_help', 'travel', 'cooking', 'health', 'religion', 'politics', 'economics', 'education', 'children', 'young_adult', 'reference', 'academic', 'other', name='book_genre')
    book_genre_enum.create(op.get_bind())
    
    # Añadir columnas
    op.add_column('books', sa.Column('book_type', book_type_enum, nullable=True))
    op.add_column('books', sa.Column('genre', book_genre_enum, nullable=True))
    op.create_index(op.f('ix_books_book_type'), 'books', ['book_type'], unique=False)
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_index(op.f('ix_books_book_type'), table_name='books')
    op.drop_column('books', 'genre')
    op.drop_column('books', 'book_type')
    
    # Eliminar tipos ENUM
    sa.Enum(name='book_type').drop(op.get_bind())
    sa.Enum(name='book_genre').drop(op.get_bind())
    # ### end Alembic commands ###
