"""add loans table

Revision ID: e301a10327c7
Revises: a4fee5145a80
Create Date: 2025-09-08 15:20:30.556386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e301a10327c7'
down_revision = 'a4fee5145a80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'active', 'returned', name='loan_status'), server_default='requested', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_book_id'), 'loans', ['book_id'], unique=False)
    op.create_index(op.f('ix_loans_borrower_id'), 'loans', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_loans_group_id'), 'loans', ['group_id'], unique=False)
    op.create_index(op.f('ix_loans_lender_id'), 'loans', ['lender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_lender_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_group_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_book_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
