"""fix_reviews_model_sqlite_compatibility

Revision ID: ef6ad3d88b86
Revises: 8cd83edee68a
Create Date: 2025-10-05 23:16:46.807305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6ad3d88b86'
down_revision = '8cd83edee68a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
